language: cpp
os: linux
dist: focal
addons:
  apt:
    packages:
      - bc
      - samtools
      - parallel
      - meson
      - ninja-build
      - libvcflib-tools
      - vcftools
jobs:
  include:
    - arch: amd64
      compiler: gcc
    - arch: arm64
      compiler: gcc
    - arch: arm64
      compiler: clang
script:
  - if [ "$TRAVIS_CPU_ARCH" = arm64 ]; then meson_opts="-Doptimization=0"; fi
  - meson build/ $meson_opts
  - ninja -C build/
  - meson test --timeout-multiplier 8 --print-errorlogs -C build/
